import Head from 'next/head'
import Container from '../components/articles/Container'
import Intro from '../components/intro/Intro'
import SocialMedia from '../components/SocialMedia'

export default function Home() {
	return (
		<div className='responsive-width'>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Intro />
			<SocialMedia />
			<Container />
		</div>
	)
}
